columnSuffix: null
handle: text
instructions: null
name: Text
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 5
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
