dateModified: 1774617261
email:
  fromEmail: $APP_EMAIL_SENDER_ADDRESS
  fromName: $APP_EMAIL_SENDER_NAME
  replyToEmail: $APP_EMAIL_SENDER_ADDRESS
  template: null
  transportSettings:
    route: ''
    token: $APP_EMAIL_LETTERMINT_TOKEN
  transportType: SomehowDigital\Craft\Lettermint\Adapter
fs:
  storage:
    hasUrls: true
    name: Storage
    settings:
      path: $APP_FILES_PATH
    type: craft\fs\Local
    url: $APP_FILES_URL
meta:
  __names__:
    1b5b6229-0f99-4c8a-84be-03bda866ff34: Page # Page
    1f3da7ed-2af0-40f7-96e4-6a943237d0aa: Pages # Pages
    2f26be8c-e6f9-474a-93ea-388a3174f124: GAMMA # GAMMA
    74f78f86-64ac-4d6c-aeef-f4b85077ed91: SINGLE # SINGLE
    1625d54e-a5f5-427c-93ad-bf872e3e115c: MULTI # MULTI
    c6bfe418-2d2a-4ce7-876c-1f06f88a1ad9: ALPHA # ALPHA
    e92bcaad-05ae-47a3-86cd-00692d6a6f84: BETA # BETA
    ed02786e-e6b9-465c-b426-aadc034ea25e: 'Public Schema' # Public Schema
plugins:
  lettermint:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  skip:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  live: true
  name: $APP_SYSTEM_NAME
  retryDuration: null
  schemaVersion: 5.9.0.8
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
