dateModified: 1777754750
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: '*'
      page: Pages
      tableAttributes:
        - status
        - section
        - postDate
        - expiryDate
        - authors
        - link
      type: native
    -
      defaultSort:
        - structure
        - asc
      defaultViewMode: ''
      disabled: false
      key: 'section:1f3da7ed-2af0-40f7-96e4-6a943237d0aa' # Pages
      page: Pages
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - authors
        - link
      type: native
elementSourcesPages:
  craft\elements\Entry:
    Pages:
      icon: file
email:
  fromEmail: $APP_EMAIL_SENDER_ADDRESS
  fromName: $APP_EMAIL_SENDER_NAME
  replyToEmail: $APP_EMAIL_SENDER_ADDRESS
  template: null
  transportSettings:
    route: ''
    token: $APP_EMAIL_LETTERMINT_TOKEN
  transportType: SomehowDigital\Craft\Lettermint\Adapter
fs:
  storage:
    hasUrls: true
    name: Storage
    settings:
      path: $APP_FILES_PATH
    type: craft\fs\Local
    url: $APP_FILES_URL
meta:
  __names__:
    1b5b6229-0f99-4c8a-84be-03bda866ff34: Page # Page
    1cc7bddd-c05d-49f7-b250-02ba33a1e021: 'Headline Level' # Headline Level
    1ef364ed-e9c3-4395-a43c-726a3fef3e9d: Header # Header
    1f3da7ed-2af0-40f7-96e4-6a943237d0aa: Pages # Pages
    2f26be8c-e6f9-474a-93ea-388a3174f124: GAMMA # GAMMA
    3ce4aff3-b884-404d-b927-52a4cfbedfe2: Headline # Headline
    7e0867a1-c157-4741-91c1-c4e789c49a32: System # System
    56dbcde8-5adc-4ecd-902f-457f212d71f4: Text # Text
    74f78f86-64ac-4d6c-aeef-f4b85077ed91: SINGLE # SINGLE
    82cb18b5-a253-49a9-bfa6-3d23d8790494: Text # Text
    1625d54e-a5f5-427c-93ad-bf872e3e115c: MULTI # MULTI
    55628bbc-83ff-4ee4-9656-37a117d650d8: Sitemap # Sitemap
    c6bfe418-2d2a-4ce7-876c-1f06f88a1ad9: ALPHA # ALPHA
    d210bdd7-c1e0-4c9e-965c-21b5f52b4a0c: Content # Content
    e006b9c9-db2a-40df-a114-1974c73e5fd7: Pages # Pages
    e92bcaad-05ae-47a3-86cd-00692d6a6f84: BETA # BETA
    ed02786e-e6b9-465c-b426-aadc034ea25e: 'Public Schema' # Public Schema
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 5.0.0.1
  lettermint:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  skip:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  stack:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  live: true
  name: $APP_SYSTEM_NAME
  retryDuration: null
  schemaVersion: 5.9.0.8
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
