defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 1b5b6229-0f99-4c8a-84be-03bda866ff34 # Page
handle: system
maxAuthors: 1
minAuthors: 1
name: System
previewTargets:
  -
    label: DEFAULT
    refresh: '1'
    urlFormat: '{slug}'
propagationMethod: all
siteSettings:
  2f26be8c-e6f9-474a-93ea-388a3174f124: # GAMMA
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: '{slug}'
  c6bfe418-2d2a-4ce7-876c-1f06f88a1ad9: # ALPHA
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: '{slug}'
  e92bcaad-05ae-47a3-86cd-00692d6a6f84: # BETA
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: '{slug}'
type: channel
